[package]
name = "chip8_emulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "chip8_core"
path = "src/emulator-core/lib.rs"

[[bin]]
name = "chip8_ui"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
sdl2 = "0.37.0"
