[package]
name = "chip8_emulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "chip8_core"
path = "chip8_core/src/lib.rs"

[[bin]]
name = "chip8_ui"
path = "chip8_ui/src/main.rs"

[dependencies]
clearscreen = "3.0.0"
crossterm = "0.27.0"
dubble = "0.1.0"
term_cursor = "0.2.1"
